### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by marrious11**
a contribution to examples\simple-extension-rewriter\README.md directory.  Approved already.
Trying to run the  Signed-off-by: Mario <66856309+marrious11@users.noreply.github.com>

### CODE REVIEW

**Comment by panglesd** [comment]
It's almost there!
You should rewrite the commit message from:
```
Update README.md

a contribution to examples\simple-extension-rewriter\README.md dir.  approved already.
Tryin to run the  Signed-off-by: Mario <66856309+marrious11@users.noreply.github.com>
```
to
```
Update README.md

Signed-off-by: Mario <66856309+marrious11@users.noreply.github.com>
```

You can do this using `git commit --amend`.

**Comment by marrious11** [comment]
Hi sir @panglesd please let me know if I succeeded in adding the __signed-off-by commit__, because I believe I have done so, except there another mistake :(

**Comment by panglesd** [comment]
You successfully signed of one commit : https://github.com/ocaml-ppx/ppxlib/pull/395/commits/86b39fb6f03d65315899779439a99d9141ec0390. Nice!

However, in this PR you have made 4 commits (you can see all of them listed here: https://github.com/ocaml-ppx/ppxlib/pull/395/commits). In order to have the CI pass, you need to have all of them signed-of...
You can see that the CI did not pass with this icon: 
image

So, I see several possibilities:
- You do not want to spend too much time fighting with Git, in which case I can modify this PR myself to let you spend more time learning OCaml or other projects
- You'd like to solve it yourself! In which case, the best would be to have only one commit in the PR, signed-off. You can either rewrite the history using `git rebase`, or "start from scratch" in another branch, since the modification is not too hard to redo.

It's up to you!

**Comment by marrious11** [comment]
Oh yes sir @panglesd, I think you are right, you can editor the PR while I focus on Ocaml and other projects.

**Review by panglesd — APPROVED** [review]

**Comment by panglesd** [comment]
I did not notice that you closed the PR before I merged it!

**Pull request merged**
