### PR TITLE
Add support for OCaml 4.13

### PR DESCRIPTION
**Pull request by kit-ty-kate**
Ports https://github.com/ocaml-ppx/ocaml-migrate-parsetree/pull/114

### CODE REVIEW

**Comment by jberdine** [comment]
I don't know if it's useful, but I pinned this PR in a 4.13-alpha1 switch and the build fails:
```
dune build --auto-promote @install
      ocamlc traverse/.ppxlib_traverse.objs/byte/ppxlib_traverse.{cmi,cmo,cmt} (exit 2)
(cd _build/default && /Users/jjb/.opam/sledge_test/bin/ocamlc.opt -w @1..3@5..28@30..39@43@46..47@49..57@61..62-40 -strict-sequence -strict-formats -short-paths -keep-locs -safe-string -g -bin-annot -I traverse/.ppxlib_traverse.objs/byte -I /Users/jjb/.opam/sledge_test/lib/stdlib-shims -I ast/.ppxlib_ast.objs/byte -I src/.ppxlib.objs/byte -I stdppx/.stdppx.objs/byte -I traverse_builtins/.ppxlib_traverse_builtins.objs/byte -no-alias-deps -opaque -o traverse/.ppxlib_traverse.objs/byte/ppxlib_traverse.cmo -c -impl traverse/ppxlib_traverse.pp.ml)
>> Fatal error: OCaml and preprocessor have incompatible versions
Fatal error: exception Misc.Fatal_error
make: *** [Makefile:5: default] Error 1
```
This is after pinning omp to #114.

**Comment by kit-ty-kate** [comment]
@jberdine thanks a lot, the magic number got bumped the day before yesterday and I hadn't seen it. It should be fixed now.

**Comment by kit-ty-kate** [comment]
Feel free to use https://github.com/kit-ty-kate/opam-alpha-repository/, it contains some of the fixes you might need.

**Comment by pitag-ha** [comment]
Thanks @kit-ty-kate! Would you mind adding a changelog entry to point out that this commit makes ppxlib compatible with 4.13? And could you also sign the commit?

**Comment by pitag-ha** [comment]
> There are still a number of ppx_* packages that don't build

@jberdine, are you referring to the packages listed [here](https://github.com/ocaml-ppx/ppxlib/issues/253#issuecomment-856169765)? Or are there more?

**Comment by pitag-ha** [comment]
> Would you mind adding a changelog entry

Never mind this anymore, since the support will already be added in 0.22.2 and we have a changelog entry for it there. I've added the `no changelog` label.

> And could you also sign the commit?

That would still be great, though!

**Comment by pitag-ha** [comment]
Just in case someone comes across this PR: this PR is currently not very active, since we've also backported it to `0.22` and released it there. Concretely, `ppxlib.0.22.2` is `4.13` compatible.

**Comment by pitag-ha** [comment]
@kit-ty-kate, could you sign the commits?

**Comment by kit-ty-kate** [comment]
@pitag-ha Done

**Review by pitag-ha — APPROVED** [review]
Thanks @kit-ty-kate!

**Pull request merged**
