### PR TITLE
New attribute in ocaml 4.08

### PR DESCRIPTION
**Pull request by hhugo**

### CODE REVIEW

**Comment by diml** [comment]
Thanks, could you sign your commit as per https://github.com/ocaml-ppx/ppxlib/blob/master/CONTRIBUTING.md?

**Comment by hhugo** [comment]
@xclerc told me he had a better version with an up to date exhaustive list of attributes. @xclerc, Should we merge your version instead ?

**Comment by xclerc** [comment]
Here is the list I came up with:
```
 let attributes =
   create_set
     [ "ocaml.alert"
     ; "ocaml.boxed"
     ; "ocaml.deprecated"
     ; "ocaml.deprecated_mutable"
     ; "ocaml.doc"
     ; "ocaml.extension_constructor"
     ; "ocaml.immediate"
     ; "ocaml.inline"
     ; "ocaml.inlined"
     ; "ocaml.local"
     ; "ocaml.noalloc"
     ; "ocaml.ppwarning"
     ; "ocaml.remove_aliases"
     ; "ocaml.specialise"
     ; "ocaml.specialised"
     ; "ocaml.tailcall"
     ; "ocaml.text"
     ; "ocaml.unboxed"
     ; "ocaml.unroll"
     ; "ocaml.unrolled"
     ; "ocaml.untagged"
     ; "ocaml.warn_on_literal_pattern"
     ; "ocaml.warnerror"
     ; "ocaml.warning"
     ]
```
I think it would be worth double-checking I did not forget one
(and/or have this list exposed somewhere upstream).

**Comment by diml** [comment]
Having it exposed upstream would be nice. In the meantime, we should commit this updated list

**Pull request closed without merging**
