### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by marrious11**
Proposed changes to the README file in the `ocaml-ppx/ppxlib` repository.
Signed-off-by: Mario <66856309+marrious11@users.noreply.github.com>

### CODE REVIEW

**Comment by Burnleydev1** [comment]
Hello, @marrious11 I would like to work you through the `sign-off` process if you don't mind.

Use `git log` to find the hash of the commit that you want to edit.

Run `git rebase -i <enter the commit hash here>` to start a rebase session that includes the commit you want to edit and its parent commit. This will open a text editor with a list of commits and instructions for how to edit them.

Find the line that corresponds to the commit you want to edit, and change the command from pick to edit. Save and close the file.

Run `git commit --amend -s`  to make changes to the commit. This will open a text editor where you can modify the commit message and/or the contents of the commit.

After making your changes, save and close the file.

Run `git rebase --continue` to continue the rebase process. This will apply your changes and modify the commit history.
When you're done, run `git push --force-with-lease origin patch-2`

**Comment by marrious11** [comment]
> Hello, @Burnleydev1! Thank you so much for the guidelines.
This section about `DCO` has been troubling me ever since I started making an attempt to contribute here.

**Review by panglesd — APPROVED** [review]
Looks good!

**Comment by marrious11** [comment]
Hi sir @panglesd, thank you 😃!
Can I close the PR now?
And too, I'd love to ask a few questions with regard to some info about the contribution.

**Comment by panglesd** [comment]
Do not close the PR! It will be merged soon, I just wanted to leave some time to other `ppxlib` maintainer to step up in case there is some problem I did not see (English is not my first language).
> And too, I'd love to ask a few questions with regard to some info about the contribution to https://github.com/ocaml-ppx/ppxlib/issues/389 as stated on the Outreachy website.

You can ask them on the #389 issue, on discord or by email!

**Comment by marrious11** [comment]
Alright sir @panglesd. Only one email was provided for us on the Outreachy website. But let me go on discord.

**Pull request merged**
