### PR TITLE
[0.22 backport] Add support for OCaml 4.13

### PR DESCRIPTION
**Pull request by kit-ty-kate**
A backport of https://github.com/ocaml-ppx/ppxlib/pull/250 for the 0.22 branch for the future release of ppxlib 0.22.2

### CODE REVIEW

**Review by pitag-ha — COMMENTED** [review]
Thanks for the backport, @kit-ty-kate! Let's see what the CI has to say once the OMP release is official.

Just two things already:
- `Ocaml_413` should also be in `versions.mli` (for `OCaml_current`, which is the version module of the compiler the project is compiled with, to be well-defined in there). If nothing is broken, that should be added by cinaps when running it.
- And we should also add a changelog entry.

If you want, I can add those 2 things on your branch.

**Comment by kit-ty-kate** [comment]
Done!

**Comment by kit-ty-kate** [comment]
Rebased to allow appveyor to take the new ocaml-migrate-parsetree release. I'm not sure which repository it uses but hopefully it works

**Comment by kit-ty-kate** [comment]
Mmh, it's not working.
@dra27 how often is fdopen's repository updated? Is there any chance of modifying the ocaml-ci-scripts' appveyor script to add fdopen's repository on top of opam-repository instead of the hard fork model?

**Comment by dra27** [comment]
It's updated frequently - it wouldn't surprise if it's there by tomorrow. It is a hard fork, though - I'm reasonably sure that if underlay (!!) opam-repository that it will mess up the compilers.

**Comment by pitag-ha** [comment]
@kit-ty-kate, I think fdopen's repository is updated now. Would you mind rebasing again for the AppVeyor CI to kick off? Or do you want me to do that?

**Comment by kit-ty-kate** [comment]
Thanks for the notification. I just did it

**Comment by dra27** [comment]
A “cheap” way to restart AppVeyor is also to close and re-open the PR 🙂

**Comment by kit-ty-kate** [comment]
All green

**Pull request merged**
