### PR TITLE
add some common cases to the doc of Ast_pattern

### PR DESCRIPTION
**Pull request by c-cube**

### CODE REVIEW

**Review by pitag-ha — COMMENTED** [review]
Thanks @c-cube, adding those two examples is a good idea!

Could you format your code and sign the commit? Once you've done that, the CI should pass.

**Comment by c-cube** [comment]
- how do I format?
- I see the commits as signed (and "verified"), what exactly is missing?

**Comment by pitag-ha** [comment]
> how do I format?

You need to have `ocamlformat.0.20.0` installed in your switch. If that's the case, you can simply run
```
dune build @fmt --auto-promote
```

> I see the commits as signed (and "verified"), what exactly is missing?

You need to sign all your commits with `--signoff` (or `-s`). If you do that, you'll see in the commit message something like
```
Signed-off-by: _your_name_ <_your_email_>
```


How have you signed them?

**Comment by c-cube** [comment]
I have `signingkey = …` in my git config. `git log --show-signature` shows that my commits are signed.

**Comment by pitag-ha** [comment]
> I have signingkey = … in my git config. git log --show-signature shows that my commits are signed.

Ok. So you've cryptographically signed your commit. What `ppxlib` contributions require is really just a sign-off of the commit. See [contributing guidelines](https://github.com/ocaml-ppx/ppxlib/blob/main/CONTRIBUTING.md#signing-commits). So if you could interactively rebase to signoff all your commits (or squash them and signoff the one commit), that would fix the CI.

**Comment by c-cube** [comment]
Sorry, I just wanted to add 5 lines of docs, I don't have time for all that.

**Pull request closed without merging**
